name: workflow

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

#    - name: Lint HTML
#      uses: super-linter/super-linter/slim@v6.6.0
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        VALIDATE_HTML: true
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        path: ./*.html
  
  dev-deploy:
    name: Deploy to Dev
    needs: build
    runs-on: dev
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
    - name: Check Artifact
      run: ls
    - name: Deploy Artifact 
      run: Copy-Item -Path artifact\* -Destination c:\server -Force

  prod-deploy:
    name: Deploy to Prod
    needs: dev-deploy
    runs-on: prod
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
    - name: Check Artifact
      run: ls
    - name: Deploy Artifact 
      run: Copy-Item -Path artifact\* -Destination c:\serverprod -Force
